namespace: web
host: app.local

imagePullPolicy: IfNotPresent

node:
  image:
    repository: api-node
    tag: v0.1.0
  replicaCount: 1
  resources: {}
  containerPort: 3000

python:
  image:
    repository: api-python
    tag: v0.1.0
  replicaCount: 1
  resources: {}
  containerPort: 5000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
