apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-node
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.node.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-node
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api-node
    spec:
      containers:
      - name: api-node
        image: "{{ .Values.node.image.repository }}:{{ .Values.node.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.node.containerPort }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.node.containerPort }}
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.node.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.node.resources | nindent 10 }}
